import { gql } from 'graphql-request';
import Head from 'next/head'
import Image from 'next/image'

import { useRouter } from 'next/router';
import graphCmsClient from '../lib/graphCmsClient';

//import productsLocal from '../products-local.json';
import styles from '../styles/Home.module.css'

function Home() {

  const data = useRouter();
  let products = Object.values(data.components["/"].props.pageProps).flat(1);
  //products = Object.values(products.components).flat(1);



  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://app.snipcart.com" />
        <link rel="preconnect" href="https://cdn.snipcart.com" />
        <link rel="stylesheet" href="https://cdn.snipcart.com/themes/v3.0.21/default/snipcart.css" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Snipcart Store
        </h1>

        {/* <div>
          <pre>
            {console.log(Object.values(data.components["/"].props.pageProps).flat(1))}
          </pre>
        </div> */}

        <p className={styles.description}>
          <a className="snipcart-checkout snipcart-summary" href="#" style={{ textDecoration: "none" }}>
            <strong>Cart: </strong> <span className="snipcart-total-price">$0.00</span>
          </a>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          {products.map(product => {
            return (
              <div key={product.id} className={styles.card}>
                <h3>{product.name}</h3>
                <img src={product["image"].url} alt={`Preview of ${product.name}`} />
                <p>{product.description}</p>
                <p>${product.price}</p>
                <p>
                  <button className="snipcart-add-item"
                    data-item-id={product.id}
                    data-item-image={product["image"].url}
                    data-item-name={product.name}
                    data-item-url="/"
                    data-item-price={product.price}
                  >
                    Add to Cart
                  </button>
                </p>
              </div>
            );
          })}
        </div>
      </main>

      <footer className={styles.footer}>
        <script async src="https://cdn.snipcart.com/themes/v3.0.21/default/snipcart.js" />
        <div hidden id="snipcart" data-api-key="NzJiYWQxN2UtYzIyNi00NGM1LThkZTMtODU2ZWQyZDljYWEzNjM3NzA2ODQxMjU1NTUxNTQ5" />
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export async function getStaticProps(context) {
  const { products } = await graphCmsClient.request(gql`
  {
    products {
      id
      name
      description
      price
      image {
        url
      }
    }
  }`
  );

  return {
    props: { products },
  }
}

export default Home;